# Generated by Django 2.2.6 on 2019-10-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_reqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurerequests',
            options={'ordering': ('client', 'client_priority')},
        ),
    ]
