# Generated by Django 2.2.6 on 2019-10-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_reqs', '0002_auto_20191016_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerequests',
            name='client_priority',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='featurerequests',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='featurerequests',
            name='target_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
