# Generated by Django 2.2.6 on 2019-10-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_reqs', '0003_auto_20191016_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurerequests',
            name='client_priority',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='featurerequests',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='featurerequests',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
